services:
  tripleview:
    build: .
    container_name: tripleview-studio
    ports:
      - "8049:80"
    environment:
      - SPARQL_ENDPOINT=http://192.168.6.123:8890/sparql/
    restart: unless-stopped